[theme]
base = "dark"
primaryColor = "white"
backgroundColor = "#323c4d"
secondaryBackgroundColor = "#012030"
textColor = "white"
font = "sans-serif"
linkColor = "#2da2e0"
baseRadius = "2rem"
borderColor = "#69c1f0"
